admins:
  NonpareilMagnitude:
    commands:
    - '*'
    description: Main administrator with full access
  TestUser:
    commands:
    - '*'
    description: Test user for automated testing
  cosmic:
    commands:
    - '*'
    description: Admin added at runtime
  cosmic2:
    commands:
    - '*'
    description: Admin added at runtime
public_commands:
- help
- status
- contacts
- youtube
- yt
- plugins
- commands
- groups
- debug
settings:
  admin_only_mode: false
  default_deny_message: Access denied. You need admin permissions to use this command.
  require_admin_for_plugins: false
