admins:
  admin1:
    commands:
    - '*'
    description: Main administrator with full access
  admin2:
    commands:
    - '*'
    description: Admin added at runtime
public_commands:
- help
- status
- ping
- stats
- admin
- reload_admin
- invite
- contacts
- groups
- debug
- youtube
- yt
settings:
  admin_only_mode: false
  default_deny_message: Access denied. You need admin permissions to use this command.
  require_admin_for_plugins: true
