# SimpleX Bot Configuration Template
# Copy this file to config.yml and customize for your setup

# Server Configuration - Use your own servers, never official ones
servers:
  smp:
    - "${SMP_SERVER_1}"
    - "${SMP_SERVER_2:-}"  # Optional backup server
  xftp:
    - "${XFTP_SERVER_1}"
    - "${XFTP_SERVER_2:-}"  # Optional backup server

# Bot Settings
bot:
  name: "${BOT_NAME:-SimpleX Bot}"
  device_name: "${DEVICE_NAME:-rename_bot}"
  websocket_url: "${WEBSOCKET_URL:-ws://localhost:3030}"
  auto_accept_contacts: ${AUTO_ACCEPT_CONTACTS:-true}
  
# Logging Configuration
logging:
  daily_rotation: true
  message_log_separate: true
  retention_days: ${LOG_RETENTION_DAYS:-30}
  log_level: "${LOG_LEVEL:-INFO}"
  
# Media Settings  
media:
  download_enabled: ${MEDIA_DOWNLOAD_ENABLED:-true}
  max_file_size: "${MAX_FILE_SIZE:-100MB}"
  allowed_types: 
    - "image"
    - "video" 
    - "document"
    - "audio"
  storage_path: "${MEDIA_STORAGE_PATH:-./media}"
  
# Command Settings
commands:
  enabled:
    - "help"
    - "echo" 
    - "status"
  prefix: "!"
  
# Security Settings
security:
  max_message_length: ${MAX_MESSAGE_LENGTH:-4096}
  rate_limit_messages: ${RATE_LIMIT_MESSAGES:-10}
  rate_limit_window: ${RATE_LIMIT_WINDOW:-60}  # seconds

# XFTP Configuration
xftp:
  cli_path: "${XFTP_CLI_PATH:-/usr/local/bin/xftp}"
  temp_dir: "${XFTP_TEMP_DIR:-./temp/xftp}"
  timeout: ${XFTP_TIMEOUT:-300}  # Download timeout in seconds
  max_file_size: ${XFTP_MAX_FILE_SIZE:-1073741824}  # 1GB limit
  chunk_parallel_limit: ${XFTP_CHUNK_PARALLEL_LIMIT:-5}  # Max parallel chunk downloads
  retry_attempts: ${XFTP_RETRY_ATTEMPTS:-3}  # Retry failed downloads
  cleanup_on_failure: ${XFTP_CLEANUP_ON_FAILURE:-true}  # Clean temp files on failure