services:
  simplex-bot:
    build: .
    container_name: simplex-bot
    user: "1000:1001"
    volumes:
      - ./bot_profile:/app/profile
      - ./logs:/app/logs
      - ./media:/app/media
      - ./plugins:/app/plugins
      - ./config.yml:/app/config.yml:ro
      - ./.env:/app/.env:ro
      # Core bot files
      - ./config_manager.py:/app/config_manager.py:ro
      - ./bot.py:/app/bot.py
      - ./file_download_manager.py:/app/file_download_manager.py:ro
      - ./message_handler.py:/app/message_handler.py:ro
      - ./websocket_manager.py:/app/websocket_manager.py:ro
      - ./xftp_client.py:/app/xftp_client.py:ro
      - ./admin_manager.py:/app/admin_manager.py:ro
      - ./invite_manager.py:/app/invite_manager.py:ro
      
      # Configuration files
      - ./admin_config.yml:/app/admin_config.yml
      - ./version.yml:/app/version.yml:ro
      
      # Startup script
      - ./start-services.sh:/app/start-services.sh
      
      # Removed unused files:
      # - connect_invitation.sh, connect.sh, check_connection.sh (standalone scripts not used by bot)
      # - websocket_connect.py, simplex_utils.py (utility scripts not imported by main bot)
      # - contact_id_resolver.py (not used by current bot implementation)
    ports:
      - "3030:3030"
    env_file:
      - .env
    environment:
      # All bot configuration environment variables
      - SMP_SERVER_1=${SMP_SERVER_1}
      - SMP_SERVER_2=${SMP_SERVER_2:-}
      - XFTP_SERVER_1=${XFTP_SERVER_1}
      - XFTP_SERVER_2=${XFTP_SERVER_2:-}
      - BOT_NAME=${BOT_NAME:-SimpleX Bot}
      - WEBSOCKET_URL=${WEBSOCKET_URL:-ws://localhost:3030}
      - AUTO_ACCEPT_CONTACTS=${AUTO_ACCEPT_CONTACTS:-true}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_RETENTION_DAYS=${LOG_RETENTION_DAYS:-30}
      - MEDIA_DOWNLOAD_ENABLED=${MEDIA_DOWNLOAD_ENABLED:-true}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-100MB}
      - MEDIA_STORAGE_PATH=${MEDIA_STORAGE_PATH:-./media}
      - MAX_MESSAGE_LENGTH=${MAX_MESSAGE_LENGTH:-4096}
      - RATE_LIMIT_MESSAGES=${RATE_LIMIT_MESSAGES:-10}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-60}
      - XFTP_CLI_PATH=${XFTP_CLI_PATH:-/usr/local/bin/xftp}
      - XFTP_TEMP_DIR=${XFTP_TEMP_DIR:-./temp/xftp}
      - XFTP_TIMEOUT=${XFTP_TIMEOUT:-300}
      - XFTP_MAX_FILE_SIZE=${XFTP_MAX_FILE_SIZE:-1073741824}
      - XFTP_RETRY_ATTEMPTS=${XFTP_RETRY_ATTEMPTS:-3}
      - XFTP_CLEANUP_ON_FAILURE=${XFTP_CLEANUP_ON_FAILURE:-true}
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - simplex-net
    command: ["bash", "/app/start-services.sh"]

  simplex-bot-test:
    build: .
    container_name: simplex-bot-test
    volumes:
      - ./:/app
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: ["python", "-m", "pytest", "tests/", "-v", "--tb=short"]
    networks:
      - simplex-net
    profiles:
      - testing

networks:
  simplex-net:
    driver: bridge